DROP DATABASE IF EXISTS burger_db;
CREATE DATABASE burger_db;
USE burger_db;

CREATE TABLE burgers(
id INT(10) AUTO_INCREMENT NOT NULL,	
burger_name VARCHAR(50) NOT NULL,
devoured BOOLEAN NOT NULL DEFAULT FALSE,
orderDate TIMESTAMP NOT NULL,
PRIMARY KEY (id)
);

SELECT * FROM burgers;

-- CREATE TABLE menu(
-- id INT(10) AUTO_INCREMENT NOT NULL,	
-- item VARCHAR(50) NOT NULL,
-- entree BOOLEAN NOT NULL DEFAULT 1,
-- PRIMARY KEY (id)
-- );